# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Hotel.create(name: 'エクシブ鳥羽')
Hotel.create(name: 'エクシブ伊豆')
Hotel.create(name: 'エクシブ白浜')
Hotel.create(name: 'エクシブ軽井沢')
Hotel.create(name: 'エクシブ鳥羽AN')
Hotel.create(name: 'エクシブ淡路島')
Hotel.create(name: 'エクシブ山中湖')
Hotel.create(name: 'エクシブ白浜AN')
Hotel.create(name: 'エクシブ琵琶湖')
Hotel.create(name: 'エクシブ蓼科')
Hotel.create(name: 'エクシブ鳴門')
Hotel.create(name: 'エクシブ初島')
Hotel.create(name: 'エクシブ鳴門SV')
Hotel.create(name: 'エクシブ浜名湖')
Hotel.create(name: 'エクシブ軽井沢SV')
Hotel.create(name: 'エクシブ鳴門SVll')
Hotel.create(name: 'エクシブ那須白河')
Hotel.create(name: 'エクシブ山中湖SV')
Hotel.create(name: 'エクシブ軽井沢パセオ')
Hotel.create(name: 'エクシブ軽井沢ムセオ')
Hotel.create(name: 'エクシブ京都八瀬離宮')
Hotel.create(name: 'エクシブ箱根離宮')
Hotel.create(name: 'エクシブ有馬離宮')
Hotel.create(name: 'エクシブ鳥羽別邸')
Hotel.create(name: 'エクシブ湯河原離宮')
Hotel.create(name: 'エクシブ六甲SV')
Hotel.create(name: '東京BCC')
Hotel.create(name: '芦屋BCC')
Hotel.create(name: 'ラグーナBCC')
Hotel.create(name: '横浜BCC')
Hotel.create(name: 'SAC高山')
Hotel.create(name: 'SAC琵琶湖')
Hotel.create(name: 'SAC日光')
